/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Building": "建筑",
    "Action": "行动",
    "Amount": "数量",
    "Are you sure you want to reset the game?": "您确定要重置游戏吗？",
    "Build New Building": "建造新建筑",
    "Count": "数数",
    "Energy": "活力",
    "Energy Demand:": "能源需求：",
    "Energy Production:": "能源生产：",
    "Factory Idle": "工厂闲置",
    "Feedback & Bug Report": "反馈和错误报告",
    "Follow = Support = More Updates, Faster": "关注 = 支持 = 更多更新，更快",
    "Forward 0/0": "前进 0/0",
    "Fulfillment Modifier:": "实现修饰符：",
    "Fulfillment:": "实现：",
    "Global": "全局",
    "Join our Discord community": "加入我们的 Discord 社区",
    "Mine": "采矿",
    "No": "不",
    "Parcels": "包裹",
    "Production": "生产",
    "Projects": "项目",
    "Research": "研究",
    "Reset Game": "重置游戏",
    "Resource": "资源",
    "Resources": "资源",
    "Start Project": "启动项目",
    "Start Research": "开始研究",
    "stone": "石头",
    "The Factory Must Grow": "工厂必须成长",
    "Upgrade": "升级",
    "Yes": "是的",
    "bricks": "砖块",
    "Buy": "购买",
    "Buy": "煤",
    "Kiln": "窑炉",
    "Sell": "出售",
    " Conveyor Belt": "输送带",
    "coal": "煤炭",
    "Coal Miner": "煤矿工人",
    "Coal Power Plant": "燃煤电厂",
    "Copper Miner": "铜矿工",
    "Copper Smelter": "铜冶炼厂",
    "copperOre": "铜矿石",
    "copperPlates": "铜板",
    "Cost:": "成本：",
    "Expansion Center": "拓展中心",
    "expansionPoints": "扩展点",
    "Forward Conveyor Belt": "正向输送带",
    "Gear Press": "齿轮压力机",
    "gears": "齿轮",
    "Iron Miner": "铁矿工",
    "Iron Smelter": "炼铁厂",
    "ironOre": "铁矿石",
    "ironPlates": "铁板",
    "Modified": "已修饰",
    "researchPoints": "研究点数",
    "Stone Miner": "石头矿工",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Gear Press - {\"ironPlates\":100,\"bricks\":200}": "齿轮压力机 - {\"铁板\":100,\"砖块\":200}",
    "Iron Miner - {\"ironPlates\":25,\"bricks\":20}": "铁矿工 - {\"铁板\":25,\"砖块\":20}",
    "Stone Miner - {\"ironPlates\":25,\"bricks\":20}": "石头矿工 - {\"铁板\":25,\"砖块\":20}",
    "Forward Conveyor Belt - {\"expansionPoints\":1}": "前向传送带 - {\"扩展点\":1}",
    "Expansion Center - {\"ironPlates\":100,\"expansionPoints\":4}": "扩展中心 - {\"铁板\":100,\"扩展点\":4}",
    "Copper Smelter - {\"bricks\":20}": "铜冶炼厂 - {\"砖块\":20}",
    "Copper Miner - {\"ironPlates\":25,\"bricks\":20}": "铜矿工 - {\"铁板\":25,\"砖块\":20}",
    "Coal Power Plant - {\"ironPlates\":25,\"bricks\":25}": "燃煤电厂 - {\"铁板\":25,\"砖块\":25}",
    "Coal Miner - {\"ironPlates\":25,\"bricks\":20}": "煤矿工人 - {\"铁板\":25,\"砖块\":20}",
    " Conveyor Belt - {\"expansionPoints\":1}": "  传送带 - {\"扩展点\":1}",
    "Cable Extruder - {\"gears\":50,\"bricks\":200}": "电缆挤出机 - {\"齿轮\":50,\"砖块\":200}",
    "Iron Smelter - {\"bricks\":20}": "炼铁厂 - {\"砖块\":20}",
    "Expansion Tech - {\"researchPoints\":4}": "扩展技术 - {\"研究点\":4}",
    "Remote Construction - {\"researchPoints\":12}": "远程建设 - {\"研究点\":12}",
    "Oil Processing - {\"researchPoints\":30}": "石油加工 - {\"研究点\":30}",
    "Steel Making - {\"researchPoints\":24}": "炼钢 - {\"研究点\":24}",
    "Win Harder - {\"researchPoints\":4000}": "赢得更大的胜利 - {\"研究点\":4000}",
    "Win the Demo - {\"researchPoints\":400}": "赢得演示 - {\"研究点\":400}",
    "Win too Hard - {\"researchPoints\":40000}": "赢得太难 - {\"研究点\":40000}",
    "Beacon Tech - {\"researchPoints\":100}": "灯塔科技 - {\"研究点\":100}",
    "Blueprint Tech - {\"researchPoints\":40}": "蓝图技术 - {\"研究点\":40}",
    "Advanced Electronics - {\"researchPoints\":36}": "高级电子产品 - {\"研究点\":36}",
    "Kiln - {\"stone\":25}": "窑炉 - {\"石头\":25}",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Backward": "后退",
    "Buildings": "建筑",
    "parcel-": "分区-",
    "Forward": "向前",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Upgrade cost: (.+) expansionPoints. New limit: (.+)$/, '升级成本：$1 扩展点。 新上限：$2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) copperPlates$/, '$1 铜板'],
    [/^([\d\.]+) gears$/, '$1 齿轮'],
    [/^([\d\.]+) copperOre$/, '$1 铜矿石'],
    [/^([\d\.]+) ironOre$/, '$1 铁矿石'],
    [/^([\d\.]+) bricks$/, '$1 砖块'],
    [/^([\d\.]+) ironPlates$/, '$1 铁板'],
    [/^([\d\.]+) coal$/, '$1 煤'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Exploration Mission ([\d\.,]+)$/, '探索任务 $1'],
    [/^Research Project ([\d\.,]+)$/, '研究项目 $1'],
    [/^([\d\.,]+) expansionPoints$/, '$1 扩展点'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Buy New Parcel \(([\d\.,]+) expansion Point\)$/, '购买新的分区（$1 扩展点）'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);